# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('bank', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2017, 11, 19, 11, 32, 27, 455717, tzinfo=utc))),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
