# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('automatic_flag', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2017, 11, 19, 11, 48, 3, 422813, tzinfo=utc))),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=20)),
                ('maturity_amount', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('payment_amount', models.IntegerField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2017, 11, 19, 11, 48, 3, 423507, tzinfo=utc))),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 11, 48, 3, 422332, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Account'),
        ),
        migrations.AddField(
            model_name='accounttransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='dashboard.Account'),
        ),
        migrations.AddField(
            model_name='accounttransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='dashboard.Account'),
        ),
    ]
